# Generated by Django 5.1.1 on 2024-10-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendedor', 'Vendedor'), ('comprador', 'Comprador')], default='comprador', max_length=50),
        ),
    ]
