# Generated by Django 5.1.1 on 2024-10-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_remove_tarea_etiqueta_remove_tarea_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
